apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../base

commonLabels:
  environment: dev

secretGenerator:
- name: weather-app-secured-configuration
  envs:
  - secured.env

images:
- name: weather-app
  newName: quay.io/calopezb/weather-app:1.0-18092024
  newTag: none