apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: weather-app
  app.kubernetes.io/component: weather-app
  app.kubernetes.io/instance: weather-app
  app.kubernetes.io/part-of: weather
  app.openshift.io/runtime: python

resources:
- deployment.yaml
- service.yaml
- route.yaml