apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-environment
  namespace: openshift-gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/clbartolome/demo-build-deploy.git
    targetRevision: master
    path: deploy/environment/
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: openshift-gitops
  syncPolicy:
    automated:
      prune: true
      selfHeal: true