apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../base

commonLabels:
  environment: live

patchesStrategicMerge:
- ./deploy-replicas-patch.yaml

secretGenerator:
- name: weather-app-secured-configuration
  envs:
  - secured.env

images:
- name: weather-app
  newName: quay.io/calopezb/weather-app
  newTag: 1.0-18092024